### ISSUE TITLE
Documentation Enhancement

### ISSUE THREAD

**Issue by prafiles** [AshishKapoor/node-api-crm#5]
Hi! Great work on the API btw. 

I was just curious of what the application is about and maybe the documentation itself wasn't making it obvious to me. While there are certainly a lot of keywords, I think mostly they lack the context in the `Readme.md`.

I think Readme should contain a generic section, focusing on following sections:

1. What is E-Commerce Blog API?
2. Getting started.
3. How to contribute?

**Comment by AshishKapoor** [comment]
On it.

**Comment by prafiles** [comment]
`Getting started` section generally mentions steps for developers to get started with the projects.

**Comment by AshishKapoor** [comment]
Take a look now.
